app/models/game.rb, app/models/piece.rb, app/models/user.rb, config/routes.rb, db/migrate/20191002020214_create_pieces.rb, db/migrate/20191002022346_add_fields_to_game_model.rb, db/schema.rb, spec/factories.rb, spec/models/piece_spec.rb
@emilykocurek and I completed the models, which at this point are just the db migrations, and the associations at the moment.  For the games model we had a few users linked with different names, which we had not done before, so I am including links to our thought process for the games model 'belongs_to' statements!
[Creating Multiple Associations With the Same Table
](https://www.spacevatican.org/2008/5/6/creating-multiple-associations-with-the-same-table/)
[Making belongs_to not required at initial creation of games](https://blog.bigbinary.com/2016/02/15/rails-5-makes-belong-to-association-required-by-default.html)
=> Creating models

app/models/game.rb
Worked with my mentor to figure out code to Add available scope to Games as requested per ticket assigned
=> Add_scope to game.rb

app/controllers/games_controller.rb, spec/controllers/games_controller_spec.rb, spec/factories.rb, spec/rails_helper.rb
Created the Show action with passing Tests/Rubocop. User association is having difficulty as there are multiple id's with black player and white player. Will have to discuss at meeting.
=> Game model show

.rubocop.yml, app/assets/stylesheets/games.scss, app/controllers/games_controller.rb, app/helpers/games_helper.rb, app/views/games/show.html.erb, spec/controllers/games_controller_spec.rb
Had to ignore my helper file bc rubocop was being difficult.
=> created chessboard on show page

app/views/games/index.html.erb
I wanted to make things a little easier for a user to create a game. I added link to new game page on game index page.
=> Created initial link to create game on game index page

.rubocop.yml, app/models/game.rb, app/models/piece.rb, spec/models/game_spec.rb, spec/models/piece_spec.rb
Created the obstructed method for pieces as long as other necessary methods.  Called on a piece it will accept arguments for the pieces location and the destination and tell if their are other pieces in the game obstructing the path.
All tests working now but may return to refactor.
=> Is obstructed

app/controllers/games_controller.rb, app/helpers/games_helper.rb, app/models/game.rb, app/views/games/show.html.erb, spec/models/game_spec.rb
Pieces populate board with a test for the method.
=> created test for populating board with pieces

app/controllers/games_controller.rb, app/models/game.rb, app/views/games/index.html.erb, app/views/games/show.html.erb, spec/controllers/games_controller_spec.rb, spec/factories.rb, spec/models/game_spec.rb
Person that creates the game will be added as the white player, the second player joining will become the black player.  Moved the populate_game method to the games update action, so pieces are not created until after the second player joins so that pieces can inherit user ids from both players.
Added a few more tests to check a few methods.
=> Add second player

app/models/piece.rb, spec/models/piece_spec.rb
Thanks for all of your help @devonproudfoot on getting this completed! If you look on localhost it will not show a piece that is being captured but you can see it by putting the following in the rails console: 
game=Game.last                        
Then Run 
game.pieces.last.move_to!(5,1)
You should see the King's override each other and then you can continue to use games.pieces.last.move_to!() and the king will move around the board and show invalid if you try to take the same color piece.
=> Capture logic

app/models/knight.rb, spec/models/movement_logic_spec.rb
Fairly straight forward. Followed the structure from Megan's valid_move? method.
=> Knight valid move

app/models/game.rb, app/models/pawn.rb, app/models/piece.rb, spec/models/movement_logic_spec.rb, spec/models/piece_spec.rb
Accounted for forward moves, double moves only from the pawn's starting space, and diagonal move only if there is an opposing piece in the spot.  It can not capture other pieces while moving forward so I may need to make some minor changes.
=> Pawn valid move

app/models/piece.rb, app/models/queen.rb, spec/models/movement_logic_spec.rb
Created Valid Move for Queen. Sorry had to ignore some of Rubocop. It was being a jerk. Can scale it down later if the code is too long.
=> valid move for Queen

app/models/queen.rb
Double checking everything is clear with codeship
=> fixing for Codeship

app/controllers/pieces_controller.rb, app/models/piece.rb
Hooked up move_to! in controller and now a piece of the opposite color can be removed from the board
=> Move to controller

app/models/queen.rb, spec/models/movement_logic_spec.rb
Attempting this again.  Other piece valid moves took a hash as an argument so I changed queen method to do the same.
=> Queen valid fix

app/models/game.rb, spec/models/game_spec.rb
'location_check?' will determine if an opponent can move their pieces onto a specific space, with 'in_check?' determining if they can move into the king specifically. I thought this might be easier to reuse code when determining checkmate or other similar methods.
=> Determine check

app/controllers/games_controller.rb, app/views/games/show.html.erb, config/routes.rb, spec/controllers/games_controller_spec.rb
Added a button to allow a player to forfeit the game.
=> Forfeit concedechange

app/assets/javascripts/games.js, app/controllers/pieces_controller.rb, app/models/game.rb, app/models/piece.rb, app/views/games/show.html.erb, db/migrate/20191104190227_add_turn_to_games.rb, db/schema.rb, spec/controllers/pieces_controller_spec.rb, spec/models/game_spec.rb, spec/models/piece_spec.rb
Added turn column to games in database, and created logic.  Tweaked some of the JS so that the turn displays on the page, and also pieces revert if ajax method fails
=> Turn logic

Gemfile.lock
I think we needed to fix the gemfile to upload to heroku, fingers crossed!
=> Fixed gemfile for heroku

app/controllers/pieces_controller.rb, spec/controllers/pieces_controller_spec.rb
I believe I found a bug in the obstructed? code. I have made a ticket in trello for it so one of the test always fails.
=> Mf user valid moves

app/views/games/index.html.erb, app/views/layouts/application.html.erb
Created a basic bootstrap navbar
=> Added navbar and few tweaks to games index

app/controllers/users_controller.rb, app/models/user.rb, app/views/users/show.html.erb
A player can now see the games they are involved with through the player profile.
=> added the ability to see games that a player is involved with in profile
